spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:32768/demo
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework: DEBUG
server:
  port: 8083
springdoc:
  api-docs:
    path: /api/v1/docs/swagger-config
    enabled: 'true'
    version: openapi_3_0
  swagger-ui:
    url: /api/v1/docs/swagger-config
    path: /api/v1/docs/swagger-ui.html